#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void intake()
{
		motor[port6] = vexRT[Btn5D]*127;
		motor[port7] = vexRT[Btn5D]*127;
		motor[port6] = vexRT[Btn6D]*-127;
		motor[port7] = vexRT[Btn6D]*-127;
}
// 2 front left
// 3 back left
// 4 front right
// 5 back right
void wheels()
{
	motor[port2] = vexRT[Ch3];
	motor[port3] = vexRT[Ch3];
	motor[port4] = vexRT[Ch2];
	motor[port5] = vexRT[Ch2];
}

void launcher()
{
	if(vexRT[Btn8D] == 1)
	{
		motor[port8] = 127;
		motor[port9] = 127;
	}
		if(vexRT[Btn7D] == 1)
	{
		motor[port8] = 0;
		motor[port9] = 0;
	}
}

void strafe()
{
	//strafeleft
	motor[port2] = vexRT[Btn5U]*-100;
	motor[port5] = vexRT[Btn5U]*-100;
	motor[port3] = vexRT[Btn5U]*100;
	motor[port4] = vexRT[Btn5U]*100;
	//straferight
	motor[port2] = vexRT[Btn6U]*100;
	motor[port5] = vexRT[Btn6U]*100;
	motor[port3] = vexRT[Btn6U]*-100;
	motor[port4] = vexRT[Btn6U]*-100;

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
// 2 front left
// 3 back left
// 4 front right
// 5 back right
wait1Msec(2500);
motor[port3] = 0;
motor[port5] = 0;
motor[port2] = 100;
motor[port4] = 100;
wait1Msec(7000);
motor[port2] = 0;
motor[port4] = 0;
motor[port8] = 127;
motor[port9] = 127;
motor[port6] = -127;
motor[port7] = -127;


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
// 2 front left
// 3 back left
// 4 front right
// 5 back right
// 6left and 7right are conveyer
task usercontrol()
{
	motor[port2] = 0;
	motor[port3] = 0;
	motor[port4] = 0;
	motor[port5] = 0;
	motor[port6] = 0;
	motor[port7] = 0;
	motor[port8] = 0;
	motor[port9] = 0;
	while(true)
	{
	intake();
	wheels();
	}
}
